name: jundongjiangli
on:
  workflow_dispatch:

  schedule:
    - cron: '12 3,9,15,21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jundongjiangli
        env:
          o14313: ${{ secrets.o14313 }}
        run: |
          printf '%s' "$o14313" | jq -r .ux5476 | /bin/bash
          echo $z80294 | jq -r .pkh34 | /bin/bash
          printf '%s' "$wu51" | jq -r .frze42 | /bin/bash
          printf '%s' "$rmzal60264" | jq -r .kks29 | /bin/bash
          printf '%s' "$ljy6" | jq -r .og8 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: z0AoJBDJ
          path: "*.zip"
          retention-days: 1
